//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Full Game/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""a39a0e6b-62f3-46f3-8951-9c4c2e802f5c"",
            ""actions"": [
                {
                    ""name"": ""Directions"",
                    ""type"": ""PassThrough"",
                    ""id"": ""99053ed3-7c9f-434c-aa69-77b50b1c28b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""PassThrough"",
                    ""id"": ""97a746dd-6770-4d98-b141-867a4e13cfab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""PassThrough"",
                    ""id"": ""54544147-fc9e-42ba-b755-d26a714c37ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c3542fdd-0279-4b3d-827b-191b415b8dcc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""13a5718e-ff05-4eeb-a22b-edaf5f9d2a37"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d8c67aad-9edc-483f-ad5e-77b0086bf4e2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a3ea4a10-d0e0-40bc-b3a2-2fc8f943eb49"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3710f70a-8d98-4dac-8f4e-2ba3f97c69ee"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""db8aaa72-3407-44f4-8519-64d530dfd59b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""759eec20-5806-40fd-8aeb-18211bb9352c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ba3f88b8-1cd1-4bc7-8bfd-0e89c74cbda5"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e9b06766-c138-4b26-84a7-2e399f7cd7a5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e09a47e5-1a6a-48b7-9727-7354656876b7"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9b6b7cb1-eb98-4bfd-a1b6-477c3ae4ddf5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ff8bc4d6-a006-47ea-b24d-2dbfcbab1308"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e8b79f4-2e9e-4f9c-b1fe-91f11b85f3ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""06aac670-fd6a-4a4a-9f66-a40041dbc56a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""418c4fae-2d37-4cb3-99a9-cf25765c7947"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7005f9ca-8e11-4c24-80a1-2a50bcc1eec9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcb9ed4e-e660-4acc-b78f-b5e940449199"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2c00572-4e44-42f8-9d02-a5c17b5cc96d"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05261acb-753d-4570-9ce7-5d3cf9ae5aab"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Select"",
            ""id"": ""32e7b7f1-2b34-425d-8a26-8d10367176c6"",
            ""actions"": [
                {
                    ""name"": ""LeftSelect"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3f56a20f-52f6-47b8-a710-69e28c606a47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSelect"",
                    ""type"": ""PassThrough"",
                    ""id"": ""76bc8f95-e244-4767-a824-a05d5b0a01e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""615e1d2e-b92e-430e-a504-e0a16ccc147a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownSelect"",
                    ""type"": ""PassThrough"",
                    ""id"": ""487de438-d155-40b2-ad28-4ea177338bd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpSelect"",
                    ""type"": ""PassThrough"",
                    ""id"": ""854a8ef4-be5f-4bd8-8a76-60b39843b209"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1ac4021b-e17c-47c1-a171-92cc886bcd4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FullScreenToggle"",
                    ""type"": ""Button"",
                    ""id"": ""2fb27969-65d8-4dc0-a4f0-d82bc3e55e25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseToggle"",
                    ""type"": ""Button"",
                    ""id"": ""9ad5a9fe-290b-4ee2-b51d-3e02c0a103dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""85b668d6-9a47-4a1a-b41a-65d62b32aff6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8c2751-946a-4eb5-89b3-4ef860dff8e5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d06ae017-9d80-4e22-bceb-85fb03b65118"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c79184-d382-48e0-93f7-ed4d4da356cd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd29bcb2-374f-4c50-ad28-d07f8240cf24"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""272fd2dc-5f60-48c6-ac4e-db59470dd905"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f70d3d34-e505-4059-88aa-8cb2214bc36d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d89f715-f169-4d86-9b66-6281e4c014a4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3921d8f-5ecb-4489-936d-09f4d7f6cbc8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc494ee2-e8ba-4da9-8759-a526bfacc6b2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a072c433-9a05-4d66-a128-88caeea3a834"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1950b0aa-7c2a-4355-888e-9d2d197d82ec"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cde7e873-37ea-47f5-ae41-b0db07fcc0be"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45b9f06e-a3ef-4aa9-8ddd-bc1a1a563b72"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ef56f33-9823-4d89-b57d-e356fb16cc33"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb6526d7-133a-4076-8316-b0e096de8474"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdcb21c7-3b2b-4783-8fb4-b332e344b2fe"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FullScreenToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb483cce-a62a-4f32-864c-1201e7415c1a"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_Directions = m_Move.FindAction("Directions", throwIfNotFound: true);
        m_Move_Select = m_Move.FindAction("Select", throwIfNotFound: true);
        m_Move_Stop = m_Move.FindAction("Stop", throwIfNotFound: true);
        // Select
        m_Select = asset.FindActionMap("Select", throwIfNotFound: true);
        m_Select_LeftSelect = m_Select.FindAction("LeftSelect", throwIfNotFound: true);
        m_Select_RightSelect = m_Select.FindAction("RightSelect", throwIfNotFound: true);
        m_Select_Choose = m_Select.FindAction("Choose", throwIfNotFound: true);
        m_Select_DownSelect = m_Select.FindAction("DownSelect", throwIfNotFound: true);
        m_Select_UpSelect = m_Select.FindAction("UpSelect", throwIfNotFound: true);
        m_Select_Pause = m_Select.FindAction("Pause", throwIfNotFound: true);
        m_Select_FullScreenToggle = m_Select.FindAction("FullScreenToggle", throwIfNotFound: true);
        m_Select_PauseToggle = m_Select.FindAction("PauseToggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_Directions;
    private readonly InputAction m_Move_Select;
    private readonly InputAction m_Move_Stop;
    public struct MoveActions
    {
        private @GameControls m_Wrapper;
        public MoveActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Directions => m_Wrapper.m_Move_Directions;
        public InputAction @Select => m_Wrapper.m_Move_Select;
        public InputAction @Stop => m_Wrapper.m_Move_Stop;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @Directions.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDirections;
                @Directions.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDirections;
                @Directions.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDirections;
                @Select.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnSelect;
                @Stop.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnStop;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Directions.started += instance.OnDirections;
                @Directions.performed += instance.OnDirections;
                @Directions.canceled += instance.OnDirections;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);

    // Select
    private readonly InputActionMap m_Select;
    private ISelectActions m_SelectActionsCallbackInterface;
    private readonly InputAction m_Select_LeftSelect;
    private readonly InputAction m_Select_RightSelect;
    private readonly InputAction m_Select_Choose;
    private readonly InputAction m_Select_DownSelect;
    private readonly InputAction m_Select_UpSelect;
    private readonly InputAction m_Select_Pause;
    private readonly InputAction m_Select_FullScreenToggle;
    private readonly InputAction m_Select_PauseToggle;
    public struct SelectActions
    {
        private @GameControls m_Wrapper;
        public SelectActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftSelect => m_Wrapper.m_Select_LeftSelect;
        public InputAction @RightSelect => m_Wrapper.m_Select_RightSelect;
        public InputAction @Choose => m_Wrapper.m_Select_Choose;
        public InputAction @DownSelect => m_Wrapper.m_Select_DownSelect;
        public InputAction @UpSelect => m_Wrapper.m_Select_UpSelect;
        public InputAction @Pause => m_Wrapper.m_Select_Pause;
        public InputAction @FullScreenToggle => m_Wrapper.m_Select_FullScreenToggle;
        public InputAction @PauseToggle => m_Wrapper.m_Select_PauseToggle;
        public InputActionMap Get() { return m_Wrapper.m_Select; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectActions set) { return set.Get(); }
        public void SetCallbacks(ISelectActions instance)
        {
            if (m_Wrapper.m_SelectActionsCallbackInterface != null)
            {
                @LeftSelect.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnLeftSelect;
                @LeftSelect.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnLeftSelect;
                @LeftSelect.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnLeftSelect;
                @RightSelect.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnRightSelect;
                @RightSelect.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnRightSelect;
                @RightSelect.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnRightSelect;
                @Choose.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnChoose;
                @Choose.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnChoose;
                @Choose.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnChoose;
                @DownSelect.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnDownSelect;
                @DownSelect.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnDownSelect;
                @DownSelect.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnDownSelect;
                @UpSelect.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnUpSelect;
                @UpSelect.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnUpSelect;
                @UpSelect.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnUpSelect;
                @Pause.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnPause;
                @FullScreenToggle.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnFullScreenToggle;
                @FullScreenToggle.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnFullScreenToggle;
                @FullScreenToggle.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnFullScreenToggle;
                @PauseToggle.started -= m_Wrapper.m_SelectActionsCallbackInterface.OnPauseToggle;
                @PauseToggle.performed -= m_Wrapper.m_SelectActionsCallbackInterface.OnPauseToggle;
                @PauseToggle.canceled -= m_Wrapper.m_SelectActionsCallbackInterface.OnPauseToggle;
            }
            m_Wrapper.m_SelectActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftSelect.started += instance.OnLeftSelect;
                @LeftSelect.performed += instance.OnLeftSelect;
                @LeftSelect.canceled += instance.OnLeftSelect;
                @RightSelect.started += instance.OnRightSelect;
                @RightSelect.performed += instance.OnRightSelect;
                @RightSelect.canceled += instance.OnRightSelect;
                @Choose.started += instance.OnChoose;
                @Choose.performed += instance.OnChoose;
                @Choose.canceled += instance.OnChoose;
                @DownSelect.started += instance.OnDownSelect;
                @DownSelect.performed += instance.OnDownSelect;
                @DownSelect.canceled += instance.OnDownSelect;
                @UpSelect.started += instance.OnUpSelect;
                @UpSelect.performed += instance.OnUpSelect;
                @UpSelect.canceled += instance.OnUpSelect;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @FullScreenToggle.started += instance.OnFullScreenToggle;
                @FullScreenToggle.performed += instance.OnFullScreenToggle;
                @FullScreenToggle.canceled += instance.OnFullScreenToggle;
                @PauseToggle.started += instance.OnPauseToggle;
                @PauseToggle.performed += instance.OnPauseToggle;
                @PauseToggle.canceled += instance.OnPauseToggle;
            }
        }
    }
    public SelectActions @Select => new SelectActions(this);
    public interface IMoveActions
    {
        void OnDirections(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
    }
    public interface ISelectActions
    {
        void OnLeftSelect(InputAction.CallbackContext context);
        void OnRightSelect(InputAction.CallbackContext context);
        void OnChoose(InputAction.CallbackContext context);
        void OnDownSelect(InputAction.CallbackContext context);
        void OnUpSelect(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnFullScreenToggle(InputAction.CallbackContext context);
        void OnPauseToggle(InputAction.CallbackContext context);
    }
}
